synchronizers:
  -
    klass: StudentsSynchronizer
    by_year: false
    by_unity: true
    dependents: [
      StudentEnrollmentSynchronizer,
      DeficienciesSynchronizer
    ]
  -
    klass: KnowledgeAreasSynchronizer
    by_year: false
    by_unity: false
    dependents: [
      DisciplinesSynchronizer
    ]
  -
    klass: RoundingTablesSynchronizer
    by_year: false
    by_unity: false
    dependents: [
      ExamRulesSynchronizer
    ]
  -
    klass: ExamRulesSynchronizer
    by_year: false
    by_unity: false
    dependents: [
      RecoveryExamRulesSynchronizer,
      CoursesSynchronizer
    ]
    dependencies: [
      RoundingTablesSynchronizer
    ]
  -
    klass: RecoveryExamRulesSynchronizer
    by_year: false
    by_unity: false
    dependencies: [
      ExamRulesSynchronizer
    ]
  -
    klass: CoursesSynchronizer
    by_year: false
    by_unity: true
    dependents: [
      GradesSynchronizer
    ]
    dependencies: [
      ExamRulesSynchronizer
    ]
  -
    klass: TeachersSynchronizer
    by_year: false
    by_unity: false
    dependents: [
      TeacherDisciplineClassroomsSynchronizer
    ]
  -
    klass: DeficienciesSynchronizer
    by_year: false
    by_unity: true
    dependencies: [
      StudentsSynchronizer
    ]
  -
    klass: DisciplinesSynchronizer
    by_year: false
    by_unity: false
    dependents: [
      SpecificStepsSynchronizer,
      TeacherDisciplineClassroomsSynchronizer,
      StudentEnrollmentDependenceSynchronizer,
      StudentEnrollmentExemptedDisciplinesSynchronizer
    ]
    dependencies: [
      KnowledgeAreasSynchronizer
    ]
  -
    klass: GradesSynchronizer
    by_year: false
    by_unity: true
    dependents: [
      ClassroomsSynchronizer
    ]
    dependencies: [
      CoursesSynchronizer
    ]
  -
    klass: ClassroomsSynchronizer
    by_year: true
    by_unity: true
    dependents: [
      SpecificStepsSynchronizer,
      TeacherDisciplineClassroomsSynchronizer,
      StudentEnrollmentClassroomSynchronizer
    ]
    dependencies: [
      GradesSynchronizer
    ]
  -
    klass: SpecificStepsSynchronizer
    by_year: true
    by_unity: true
    dependencies: [
      DisciplinesSynchronizer,
      ClassroomsSynchronizer
    ]
  -
    klass: TeacherDisciplineClassroomsSynchronizer
    by_year: true
    by_unity: true
    dependencies: [
      TeachersSynchronizer,
      DisciplinesSynchronizer,
      ClassroomsSynchronizer
    ]
  -
    klass: StudentEnrollmentSynchronizer
    by_year: true
    by_unity: true
    dependents: [
      StudentEnrollmentClassroomSynchronizer,
      StudentEnrollmentDependenceSynchronizer,
      StudentEnrollmentExemptedDisciplinesSynchronizer
    ]
    dependencies: [
      StudentsSynchronizer
    ]
  -
    klass: StudentEnrollmentClassroomSynchronizer
    by_year: true
    by_unity: true
    dependencies: [
      StudentEnrollmentSynchronizer,
      ClassroomsSynchronizer
    ]
  -
    klass: StudentEnrollmentDependenceSynchronizer
    by_year: true
    by_unity: true
    dependencies: [
      StudentEnrollmentSynchronizer,
      DisciplinesSynchronizer
    ]
  -
    klass: StudentEnrollmentExemptedDisciplinesSynchronizer
    by_year: true
    by_unity: true
    dependencies: [
      StudentEnrollmentSynchronizer,
      DisciplinesSynchronizer
    ]
